"""Seed 30 clientes del archivo ENUNCIADOS_30_CASOS_CREDITO_FLUJO_MOVIL.md"""
import uuid
from datetime import date
from app.core.database import SessionLocal, engine, Base
from app.core.security import hash_password
from app.models.models import Cliente, UsuarioCliente, Agencia, Asesor, Credito, CarteraDiaria

Base.metadata.create_all(bind=engine)
db = SessionLocal()

pw = hash_password("Prymera2024")

# Asegurar que exista al menos una agencia
agencia = db.query(Agencia).first()
if not agencia:
    agencia = Agencia(id=uuid.uuid4(), cod_agencia="AG001", nombre="Agencia Principal", region="Junin", lat=-12.0664, lng=-75.2048)
    db.add(agencia)
    db.commit()

# Asegurar que exista al menos un asesor
asesor = db.query(Asesor).filter(Asesor.codigo_empleado == "0001").first()
if not asesor:
    from app.core.security import hash_password
    asesor = Asesor(id=uuid.uuid4(), codigo_empleado="0001", nombres="Maria", apellidos="Quispe",
                    agencia_id=agencia.id, perfil="operador", password_hash=hash_password("Prymera2024"))
    db.add(asesor)
    db.commit()

casos = [
    {
        "nombre": "Anaximandro Quispe",
        "apellidos": "Quispe",
        "documento": "40118120",
        "telefono": "964110201",
        "negocio": "Bodega Don Anaxi",
        "tipo": "Comercio",
        "ubicacion": "El Tambo",
        "antiguedad": 48,
        "ingreso": 2200.00,
        "gasto": 900.00,
        "lat": -12.0581,
        "lng": -75.2027,
    },
    {
        "nombre": "Eulalia Mamani",
        "apellidos": "Mamani",
        "documento": "41223341",
        "telefono": "964110202",
        "negocio": "Picanteria La Eulalia",
        "tipo": "Restaurante",
        "ubicacion": "Chilca",
        "antiguedad": 36,
        "ingreso": 3000.00,
        "gasto": 1400.00,
        "lat": -12.0921,
        "lng": -75.2105,
    },
    {
        "nombre": "Teofilo Huaman",
        "apellidos": "Huaman",
        "documento": "42330336",
        "telefono": "964110203",
        "negocio": "Maderas Huaman",
        "tipo": "Carpinteria",
        "ubicacion": "Pilcomayo",
        "antiguedad": 60,
        "ingreso": 4200.00,
        "gasto": 1800.00,
        "lat": -12.0496,
        "lng": -75.2486,
    },
    {
        "nombre": "Casandra Flores",
        "apellidos": "Flores",
        "documento": "43440349",
        "telefono": "964110204",
        "negocio": "Distribuidora Casandra",
        "tipo": "Abarrotes",
        "ubicacion": "Huancayo",
        "antiguedad": 84,
        "ingreso": 7000.00,
        "gasto": 2600.00,
        "lat": -12.0651,
        "lng": -75.2049,
    },
    {
        "nombre": "Demostenes Rojas",
        "apellidos": "Rojas",
        "documento": "40556071",
        "telefono": "964110205",
        "negocio": "Ferreteria El Constructor",
        "tipo": "Ferreteria",
        "ubicacion": "San Agustin de Cajas",
        "antiguedad": 30,
        "ingreso": 5200.00,
        "gasto": 2100.00,
        "lat": -12.0188,
        "lng": -75.2271,
    },
    {
        "nombre": "Hipatia Condori",
        "apellidos": "Condori",
        "documento": "41669066",
        "telefono": "964110206",
        "negocio": "Confecciones Hipatia",
        "tipo": "Textil",
        "ubicacion": "El Tambo",
        "antiguedad": 54,
        "ingreso": 6800.00,
        "gasto": 2900.00,
        "lat": -12.0612,
        "lng": -75.2118,
    },
    {
        "nombre": "Anibal Vargas",
        "apellidos": "Vargas",
        "documento": "43773379",
        "telefono": "964110207",
        "negocio": "Transportes Anibal",
        "tipo": "Transporte",
        "ubicacion": "Concepcion",
        "antiguedad": 42,
        "ingreso": 9500.00,
        "gasto": 4200.00,
        "lat": -11.9182,
        "lng": -75.3142,
    },
    {
        "nombre": "Penelope Apaza",
        "apellidos": "Apaza",
        "documento": "40886086",
        "telefono": "964110208",
        "negocio": "Granja Penelope",
        "tipo": "Avicola",
        "ubicacion": "Sapallanga",
        "antiguedad": 72,
        "ingreso": 8800.00,
        "gasto": 3600.00,
        "lat": -12.1581,
        "lng": -75.1762,
    },
    {
        "nombre": "Heraclito Ccahua",
        "apellidos": "Ccahua",
        "documento": "41990091",
        "telefono": "964110209",
        "negocio": "Importaciones Heraclito",
        "tipo": "Comercio",
        "ubicacion": "Huancayo",
        "antiguedad": 96,
        "ingreso": 12000.00,
        "gasto": 5000.00,
        "lat": -12.0668,
        "lng": -75.2103,
    },
    {
        "nombre": "Cleopatra Soto",
        "apellidos": "Soto",
        "documento": "43003039",
        "telefono": "964110210",
        "negocio": "Botica Cleopatra",
        "tipo": "Farmacia",
        "ubicacion": "Chupaca",
        "antiguedad": 66,
        "ingreso": 11000.00,
        "gasto": 4400.00,
        "lat": -12.0560,
        "lng": -75.2870,
    },
    {
        "nombre": "Esquilo Ramos",
        "apellidos": "Ramos",
        "documento": "40110010",
        "telefono": "964110211",
        "negocio": "Minimarket Esquilo",
        "tipo": "Bodega",
        "ubicacion": "Huayucachi",
        "antiguedad": 24,
        "ingreso": 1900.00,
        "gasto": 800.00,
        "lat": -12.1339,
        "lng": -75.2090,
    },
    {
        "nombre": "Ariadna Quispe",
        "apellidos": "Quispe",
        "documento": "41226021",
        "telefono": "964110212",
        "negocio": "Estilos Ariadna",
        "tipo": "Peluqueria",
        "ubicacion": "El Tambo",
        "antiguedad": 40,
        "ingreso": 3300.00,
        "gasto": 1300.00,
        "lat": -12.0573,
        "lng": -75.2161,
    },
    {
        "nombre": "Sofocles Huanca",
        "apellidos": "Huanca",
        "documento": "43336033",
        "telefono": "964110213",
        "negocio": "Panaderia Sofocles",
        "tipo": "Panaderia",
        "ubicacion": "Sicaya",
        "antiguedad": 58,
        "ingreso": 5600.00,
        "gasto": 2300.00,
        "lat": -12.0228,
        "lng": -75.3134,
    },
    {
        "nombre": "Casiopea Torres",
        "apellidos": "Torres",
        "documento": "40550055",
        "telefono": "964110214",
        "negocio": "Taller Casiopea",
        "tipo": "Mecanica",
        "ubicacion": "Pilcomayo",
        "antiguedad": 50,
        "ingreso": 7400.00,
        "gasto": 3000.00,
        "lat": -12.0512,
        "lng": -75.2451,
    },
    {
        "nombre": "Aristofanes Cruz",
        "apellidos": "Cruz",
        "documento": "41669166",
        "telefono": "964110215",
        "negocio": "Insumos Aristofanes",
        "tipo": "Agropecuario",
        "ubicacion": "Orcotuna",
        "antiguedad": 78,
        "ingreso": 8200.00,
        "gasto": 3300.00,
        "lat": -11.9760,
        "lng": -75.3361,
    },
    {
        "nombre": "Calipso Mendoza",
        "apellidos": "Mendoza",
        "documento": "43880088",
        "telefono": "964110216",
        "negocio": "Calzados Calipso",
        "tipo": "Calzado",
        "ubicacion": "Huancayo",
        "antiguedad": 62,
        "ingreso": 7900.00,
        "gasto": 3100.00,
        "lat": -12.0689,
        "lng": -75.2055,
    },
    {
        "nombre": "Demetrio Quispe",
        "apellidos": "Quispe",
        "documento": "40119019",
        "telefono": "964110217",
        "negocio": "Mayorista Demetrio",
        "tipo": "Comercio",
        "ubicacion": "Jauja",
        "antiguedad": 90,
        "ingreso": 11500.00,
        "gasto": 4700.00,
        "lat": -11.7752,
        "lng": -75.4995,
    },
    {
        "nombre": "Antigona Flores",
        "apellidos": "Flores",
        "documento": "41226126",
        "telefono": "964110218",
        "negocio": "Recreo Antigona",
        "tipo": "Restaurante",
        "ubicacion": "Concepcion",
        "antiguedad": 70,
        "ingreso": 9200.00,
        "gasto": 3900.00,
        "lat": -11.9201,
        "lng": -75.3110,
    },
    {
        "nombre": "Pitagoras Rojas",
        "apellidos": "Rojas",
        "documento": "43339033",
        "telefono": "964110219",
        "negocio": "Ferreteria Pitagoras",
        "tipo": "Ferreteria",
        "ubicacion": "El Tambo",
        "antiguedad": 100,
        "ingreso": 13000.00,
        "gasto": 5200.00,
        "lat": -12.0599,
        "lng": -75.2143,
    },
    {
        "nombre": "Berenice Apaza",
        "apellidos": "Apaza",
        "documento": "40556056",
        "telefono": "964110220",
        "negocio": "Tejidos Berenice",
        "tipo": "Textil",
        "ubicacion": "San Jeronimo de Tunan",
        "antiguedad": 46,
        "ingreso": 8600.00,
        "gasto": 3500.00,
        "lat": -11.9871,
        "lng": -75.2899,
    },
    {
        "nombre": "Anaxagoras Huaman",
        "apellidos": "Huaman",
        "documento": "43889089",
        "telefono": "964110221",
        "negocio": "Carga Anaxagoras",
        "tipo": "Transporte",
        "ubicacion": "Huancayo",
        "antiguedad": 84,
        "ingreso": 14000.00,
        "gasto": 5800.00,
        "lat": -12.0644,
        "lng": -75.2088,
    },
    {
        "nombre": "Climene Vargas",
        "apellidos": "Vargas",
        "documento": "41003001",
        "telefono": "964110222",
        "negocio": "Avicola Climene",
        "tipo": "Avicola",
        "ubicacion": "Sapallanga",
        "antiguedad": 76,
        "ingreso": 13500.00,
        "gasto": 5500.00,
        "lat": -12.1560,
        "lng": -75.1790,
    },
    {
        "nombre": "Epaminondas Soto",
        "apellidos": "Soto",
        "documento": "40115011",
        "telefono": "964110223",
        "negocio": "Bodega Epaminondas",
        "tipo": "Bodega",
        "ubicacion": "Pucara",
        "antiguedad": 28,
        "ingreso": 2600.00,
        "gasto": 1000.00,
        "lat": -12.1701,
        "lng": -75.1611,
    },
    {
        "nombre": "Lisistrata Ramos",
        "apellidos": "Ramos",
        "documento": "41336036",
        "telefono": "964110224",
        "negocio": "Variedades Lisistrata",
        "tipo": "Comercio",
        "ubicacion": "Huancayo",
        "antiguedad": 52,
        "ingreso": 4100.00,
        "gasto": 1700.00,
        "lat": -12.0633,
        "lng": -75.2071,
    },
    {
        "nombre": "Filoctetes Cruz",
        "apellidos": "Cruz",
        "documento": "41552052",
        "telefono": "964110225",
        "negocio": "Cevicheria Filoctetes",
        "tipo": "Restaurante",
        "ubicacion": "Chilca",
        "antiguedad": 18,
        "ingreso": 3800.00,
        "gasto": 2200.00,
        "lat": -12.0930,
        "lng": -75.2090,
    },
    {
        "nombre": "Calirroe Mendoza",
        "apellidos": "Mendoza",
        "documento": "41888088",
        "telefono": "964110226",
        "negocio": "Calzados Calirroe",
        "tipo": "Calzado",
        "ubicacion": "El Tambo",
        "antiguedad": 34,
        "ingreso": 5000.00,
        "gasto": 2600.00,
        "lat": -12.0588,
        "lng": -75.2129,
    },
    {
        "nombre": "Tucidides Quispe",
        "apellidos": "Quispe",
        "documento": "42220022",
        "telefono": "964110227",
        "negocio": "Ferreteria Tucidides",
        "tipo": "Ferreteria",
        "ubicacion": "Concepcion",
        "antiguedad": 40,
        "ingreso": 6200.00,
        "gasto": 2900.00,
        "lat": -11.9176,
        "lng": -75.3155,
    },
    {
        "nombre": "Aquiles Mamani",
        "apellidos": "Mamani",
        "documento": "43337037",
        "telefono": "964110228",
        "negocio": "Comercial Aquiles",
        "tipo": "Comercio",
        "ubicacion": "Huancayo",
        "antiguedad": 60,
        "ingreso": 9000.00,
        "gasto": 3600.00,
        "lat": -12.0657,
        "lng": -75.2099,
    },
    {
        "nombre": "Medea Apaza",
        "apellidos": "Apaza",
        "documento": "41884084",
        "telefono": "964110229",
        "negocio": "Bodega Medea",
        "tipo": "Bodega",
        "ubicacion": "Pilcomayo",
        "antiguedad": 22,
        "ingreso": 1800.00,
        "gasto": 1100.00,
        "lat": -12.0489,
        "lng": -75.2470,
    },
    {
        "nombre": "Esquines Rojas",
        "apellidos": "Rojas",
        "documento": "43334034",
        "telefono": "964110230",
        "negocio": "Fletes Esquines",
        "tipo": "Transporte",
        "ubicacion": "Jauja",
        "antiguedad": 30,
        "ingreso": 7000.00,
        "gasto": 3200.00,
        "lat": -11.7740,
        "lng": -75.5010,
    },
]

insertados = 0
for c in casos:
    existe = db.query(Cliente).filter(Cliente.numero_documento == c["documento"]).first()
    if not existe:
        cliente = Cliente(
            id=uuid.uuid4(),
            numero_documento=c["documento"],
            nombres=c["nombre"],
            apellidos=c["apellidos"],
            telefono=c["telefono"],
            tipo_negocio=c["tipo"],
            nombre_negocio=c["negocio"],
            ingresos_estimados=c["ingreso"],
            calificacion_sbs="Normal",
            fecha_nacimiento=date(1980, 1, 1),
        )
        db.add(cliente)
        db.flush()

        usuario = UsuarioCliente(
            id=uuid.uuid4(),
            cliente_id=cliente.id,
            username=c["documento"],
            password_hash=pw,
            activo=True,
        )
        db.add(usuario)

        cartera = CarteraDiaria(
            id=uuid.uuid4(),
            asesor_id=asesor.id,
            cliente_id=cliente.id,
            agencia_id=agencia.id,
            fecha_asignacion=date.today(),
            tipo_gestion="NUEVA_SOLICITUD",
            prioridad="normal",
            score_prioridad=50,
        )
        db.add(cartera)

        insertados += 1
        print(f"  [{insertados:2d}] {c['nombre'][:20]:20s} | DNI {c['documento']} | {c['negocio']}")

db.commit()
db.close()
print(f"\nTotal: {insertados} clientes insertados (de 30 casos)")
print("Username = DNI, Password = Prymera2024 (para todos)")
print("Asesor asignado: 0001 (Maria Quispe)")
